### ISSUE TITLE
attempt to gracefully stop a node results in an infinite hang

### ISSUE THREAD

**Issue by adameat** [ydb-platform/ydb#11299]
```
Current KQP shutdown state: spent 0 seconds, not started yet
2024-11-06T06:05:09.482383Z :TENANT_POOL NOTICE: Forward drain node to local.
2024-11-06T06:05:09.482414Z :LOCAL NOTICE: Forward drain node to local, hive id: 72057594037968897
2024-11-06T06:05:09.482423Z :LOCAL NOTICE: Send drain node to hive: 72057594037968897. Online tablets: 0
2024-11-06T06:05:09.489927Z :LOCAL NOTICE: Drain node result received. Online tablets: 0
^[[ACurrent KQP shutdown state: spent 3.002927 seconds, not started yet
Current KQP shutdown state: spent 6.005855 seconds, not started yet
Current KQP shutdown state: spent 9.008864 seconds, not started yet
Current KQP shutdown state: spent 12.011981 seconds, not started yet
2024-11-06T06:05:24.482586Z :LOCAL NOTICE: Drain node result received: timeout. Online tablets: 0
Current KQP shutdown state: spent 15.014917 seconds, not started yet
Current KQP shutdown state: spent 18.017859 seconds, not started yet
Current KQP shutdown state: spent 21.02111 seconds, not started yet
Current KQP shutdown state: spent 24.024046 seconds, not started yet
Current KQP shutdown state: spent 27.027211 seconds, not started yet
Failed to gracefully shutdown KQP after 30 seconds: spent 30.030259 seconds, 0 sessions to shutdown left
Drain completed.
2024-11-06T06:05:39.519722Z :BS_NODE ERROR: {NW42@node_warden_pipe.cpp:55} Handle(TEvTabletPipe::TEvClientDestroyed) ClientId# [50016:7432291146339591378:16] ServerId# [7:7432291146843470689:1572] TabletId# 72057594037932033 PipeClientId# [50016:7432291146339591378:16]
GRpc shutdown warning: left infly: 7, spent: 3.025221 sec
GRpc shutdown warning: left infly: 7, spent: 6.054668 sec
GRpc shutdown warning: left infly: 7, spent: 9.083688 sec
GRpc shutdown warning: left infly: 7, spent: 12.10871 sec
GRpc shutdown warning: left infly: 7, spent: 15.136049 sec
GRpc shutdown warning: left infly: 7, spent: 18.16558 sec
GRpc shutdown warning: left infly: 7, spent: 21.191074 sec
GRpc shutdown warning: left infly: 7, spent: 24.216498 sec
GRpc shutdown warning: left infly: 7, spent: 27.246033 sec
GRpc shutdown warning: failed to shutdown all connections, left infly: 7, spent: 30.005969 sec
^[[1;5A^C^C^C^C^C^C^C^C
^C^C^C^C^C

```

**Comment by adameat** [comment]
```
0x00007ffff7f94cd7 in __pthread_clockjoin_ex () from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) bt
#0  0x00007ffff7f94cd7 in __pthread_clockjoin_ex () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000e25d43e in (anonymous namespace)::TPosixThread::Join (this=<optimized out>) at /home/xenoxeno/work/ydb/util/system/thread.cpp:198
#2  TThread::Join (this=0x5555fd491f88) at /home/xenoxeno/work/ydb/util/system/thread.cpp:319
#3  0x000000000ee9d6ac in NActors::TBasicExecutorPool::Shutdown (this=0x5555ff792000) at /home/xenoxeno/work/ydb/ydb/library/actors/core/executor_pool_basic.cpp:500
#4  0x000000000ee929b1 in NActors::TCpuManager::Shutdown (this=0x5555fe36f400) at /home/xenoxeno/work/ydb/ydb/library/actors/core/cpu_manager.cpp:97
#5  0x000000000ee903c0 in NActors::TActorSystem::Stop (this=0x5555ff8ae170) at /home/xenoxeno/work/ydb/ydb/library/actors/core/actorsystem.cpp:330
#6  0x0000000017e3b36a in NKikimr::TKikimrRunner::KikimrStop (this=0x5555ffd7cc30, graceful=<optimized out>) at /home/xenoxeno/work/ydb/ydb/core/driver_lib/run/run.cpp:1839
#7  0x000000001793056c in NKikimr::MainRun (runConfig=..., factories=...) at /home/xenoxeno/work/ydb/ydb/core/driver_lib/run/main.cpp:50
#8  0x0000000017de710c in NKikimr::NDriverClient::TClientCommandServer::Run (this=0x5555ffb85b00, config=...) at /home/xenoxeno/work/ydb/ydb/core/driver_lib/cli_utils/cli_cmds_server.cpp:51
#9  0x0000000017965ac3 in NKikimr::NDriverClient::NewClient (argc=argc@entry=16, argv=argv@entry=0x7fffffffe158, factories=...) at /home/xenoxeno/work/ydb/ydb/core/driver_lib/cli_utils/cli_cmds_root.cpp:72
#10 0x0000000017932043 in NKikimr::Main (argc=<optimized out>, argc@entry=16, argv=0x7fffffffe160, argv@entry=0x7fffffffe158, factories=...) at /home/xenoxeno/work/ydb/ydb/core/driver_lib/run/main.cpp:148
#11 0x0000000017932ffa in ParameterizedMain (argc=-474514992, argc@entry=16, argv=0x0, argv@entry=0x7fffffffe158, factories=...) at /home/xenoxeno/work/ydb/ydb/core/driver_lib/run/main.cpp:196
#12 0x000000000e1ab75b in main (argc=16, argv=0x7fffffffe158) at /home/xenoxeno/work/ydb/ydb/apps/ydbd/main.cpp:24
(gdb) 
```

**Comment by adameat** [comment]
full stack
[text (3).txt](https://github.com/user-attachments/files/17655941/text.3.txt)
