### ISSUE TITLE
[coredump] #0 NDateTimeHelpers::SumWithSaturation<unsigned long>

### ISSUE THREAD

**Issue by maximyurchuk** [ydb-platform/ydb#12325]
The coredump was found during TPC-H workload and some other loads. GDB output:
```
Core was generated by `/Berkanavt/kikimr/bin/kikimr server --yaml-config /Berkanavt/kikimr/cfg/config.'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  NDateTimeHelpers::SumWithSaturation<unsigned long> (b=6885, 
    a=<optimized out>) at /home/maxim-yurchuk/ydb/util/datetime/base.h:639
639     /home/maxim-yurchuk/ydb/util/datetime/base.h: No such file or directory.
[Current thread is 1 (Thread 0x7fda2cedc700 (LWP 1171730))]
#0  NDateTimeHelpers::SumWithSaturation<unsigned long> (b=6885, 
    a=<optimized out>) at /home/maxim-yurchuk/ydb/util/datetime/base.h:639
#1  operator+ (l=..., r=...)
    at /home/maxim-yurchuk/ydb/util/datetime/base.h:667
#2  TDuration::operator+=<TDuration> (this=<optimized out>, t=...)
    at /home/maxim-yurchuk/ydb/util/datetime/base.h:319
#3  NKikimr::NOlap::NReader::NPlain::IFetchingStep::AddDuration (this=0x0, 
    d=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h:37
#4  NKikimr::NOlap::NReader::NPlain::TFetchingScript::AddStepDuration (
    this=0x44d6304a3178, index=0, d=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h:84
#5  NKikimr::NOlap::NReader::NPlain::TFetchingScriptCursor::FlushDuration (
    this=0x44d60d87d4e8)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h:137
#6  0x00000000160fde50 in NKikimr::NOlap::NReader::NPlain::TFetchingScriptCursor::Next (this=0x44d60d87d4e8)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h:159
#7  NKikimr::NOlap::NReader::NPlain::TAllocateMemoryStep::TFetchingStepAllocation::DoOnAllocated (this=0x44d60d87d4b8, guard=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp:189
#8  0x00000000160b0ab3 in NKikimr::NOlap::NGroupedMemoryManager::IAllocation::OnAllocated (this=0x44d60d87d4b8, guard=..., allocation=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/usage/abstract.cpp:29
#9  0x000000001d6feba8 in NKikimr::NOlap::NGroupedMemoryManager::TAllocationInfo::Allocate (this=0x44d623721258, ownerId=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/allocation.h:57
#10 0x000000001d70658e in NKikimr::NOlap::NGroupedMemoryManager::TAllocationGroups::Allocate (this=0x44d619e831a8, isPriorityProcess=true, process=..., 
    allocationsLimit=1)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/group.cpp:41
#11 0x000000001d6fb3ec in NKikimr::NOlap::NGroupedMemoryManager::TProcessMemoryScope::TryAllocateWaiting (this=0xe0076, allocationsCountLimit=1, 
    isPriorityProcess=<optimized out>)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/process.h:107
#12 NKikimr::NOlap::NGroupedMemoryManager::TProcessMemory::TryAllocateWaiting
    (this=0x44d6637dd710, allocationsCountLimit=1)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/process.h:256
#13 NKikimr::NOlap::NGroupedMemoryManager::TManager::TryAllocateWaiting (
    this=this@entry=0x44d63f852708)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/manager.cpp:52
#14 0x000000001d6fb814 in NKikimr::NOlap::NGroupedMemoryManager::TManager::UnregisterAllocation (this=0x44d63f852708, externalProcessId=<optimized out>, 
    externalScopeId=123, allocationId=56712)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/manager.cpp:66
#15 0x000000000ef25c37 in NActors::TGenericExecutorThread::Execute (
    this=this@entry=0x44d63f653800, mailbox=mailbox@entry=0x44d6385a0a80, 
    isTailExecution=<optimized out>)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:248
#16 0x000000000ef29401 in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*)::$_0::operator()(NActors::TMailbox*, bool) const (
    this=this@entry=0x7fda2cea2f90, mailbox=mailbox@entry=0x44d6385a0a80, 
    isTailExecution=false)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:425
#17 0x000000000ef28f53 in NActors::TGenericExecutorThread::ProcessExecutorPool
    (this=this@entry=0x44d63f653800, pool=<optimized out>)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:479
#18 0x000000000ef29b56 in NActors::TExecutorThread::ThreadProc (
    this=0x44d63f653800)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:510
#19 0x000000000e343898 in (anonymous namespace)::TPosixThread::ThreadProxy (
    arg=0x44d63d046630) at /home/maxim-yurchuk/ydb/util/system/thread.cpp:244
#20 0x00007fda4eb13609 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#21 0x00007fda4ea33353 in clone () from /lib/x86_64-linux-gnu/libc.so.6

```

Found in:
On host ydb-sas-testing-0000.search.yandex.net, /coredumps/kikimr.User.1171577.11
On host ydb-sas-testing-0000.search.yandex.net, /coredumps/kikimr.User.1175770.11
On host ydb-sas-testing-0000.search.yandex.net, /coredumps/kikimr.User.1180749.11
On host ydb-sas-testing-0000.search.yandex.net, /coredumps/kikimr.User.1183316.11
On host ydb-sas-testing-0000.search.yandex.net, /coredumps/kikimr.User.1186544.11
On host ydb-sas-testing-0000.search.yandex.net, /coredumps/kikimr.User.1195455.11
On host ydb-sas-testing-0000.search.yandex.net, /coredumps/kikimr.User.1198563.11
On host ydb-sas-testing-0000.search.yandex.net, /coredumps/kikimr.User.1202150.11
On host ydb-sas-testing-0001.search.yandex.net, /coredumps/kikimr.User.3348234.11
On host ydb-sas-testing-0001.search.yandex.net, /coredumps/kikimr.User.3379291.11
On host ydb-sas-testing-0001.search.yandex.net, /coredumps/kikimr.User.3422600.11
On host ydb-sas-testing-0001.search.yandex.net, /coredumps/kikimr.User.3424654.11
On host ydb-sas-testing-0001.search.yandex.net, /coredumps/kikimr.User.3425058.11
On host ydb-sas-testing-0002.search.yandex.net, /coredumps/kikimr.User.3586959.11
On host ydb-sas-testing-0002.search.yandex.net, /coredumps/kikimr.User.3621500.11
On host ydb-sas-testing-0002.search.yandex.net, /coredumps/kikimr.User.3624141.11
On host ydb-sas-testing-0002.search.yandex.net, /coredumps/kikimr.User.3631405.11
On host ydb-sas-testing-0003.search.yandex.net, /coredumps/kikimr.User.501057.11
On host ydb-sas-testing-0003.search.yandex.net, /coredumps/kikimr.User.502723.11
On host ydb-sas-testing-0003.search.yandex.net, /coredumps/kikimr.User.517531.11
On host ydb-sas-testing-0003.search.yandex.net, /coredumps/kikimr.User.546128.11
On host ydb-sas-testing-0003.search.yandex.net, /coredumps/kikimr.User.554905.11
On host ydb-sas-testing-0004.search.yandex.net, /coredumps/kikimr.User.3289753.11
On host ydb-sas-testing-0004.search.yandex.net, /coredumps/kikimr.User.3327398.11
On host ydb-sas-testing-0004.search.yandex.net, /coredumps/kikimr.User.3341894.11
On host ydb-sas-testing-0004.search.yandex.net, /coredumps/kikimr.User.3343753.11
On host ydb-sas-testing-0004.search.yandex.net, /coredumps/kikimr.User.3350271.11
On host ydb-sas-testing-0005.search.yandex.net, /coredumps/kikimr.User.3835155.11
On host ydb-sas-testing-0005.search.yandex.net, /coredumps/kikimr.User.3888339.11
On host ydb-sas-testing-0006.search.yandex.net, /coredumps/kikimr.User.2635958.11
On host ydb-sas-testing-0006.search.yandex.net, /coredumps/kikimr.User.2662485.11
On host ydb-sas-testing-0006.search.yandex.net, /coredumps/kikimr.User.2682440.11
On host ydb-sas-testing-0006.search.yandex.net, /coredumps/kikimr.User.2691757.11
On host ydb-sas-testing-0006.search.yandex.net, /coredumps/kikimr.User.2701598.11
On host ydb-sas-testing-0006.search.yandex.net, /coredumps/kikimr.User.2705665.11
On host ydb-sas-testing-0007.search.yandex.net, /coredumps/kikimr.User.2123984.11
On host ydb-sas-testing-0007.search.yandex.net, /coredumps/kikimr.User.2129132.11
On host ydb-sas-testing-0007.search.yandex.net, /coredumps/kikimr.User.2131664.11
On host ydb-sas-testing-0007.search.yandex.net, /coredumps/kikimr.User.2175911.11

```
maxim-yurchuk@ydb-sas-testing-0000:~$ /Berkanavt/kikimr/bin/kikimr -V
Git info:
    Commit: 73759b64031eccfc62243c58f9b086513e0e1509
    Branch: heads/main
    Author: Semyon <yentsovsemyon@ydb.tech>
    Summary: fix TTL initialization from DB on CS (#12210)

Other info:
    Build by: maxim-yurchuk
    Top src dir: /home/maxim-yurchuk/ydb
    Top build dir: /home/maxim-yurchuk/.ya/build
    Hostname: yurchuk-turbo.vla.yp-c.yandex.net
    Host information: 
        Linux yurchuk-turbo.vla.yp-c.yandex.net 5.4.210-39.1 #1 SMP Thu Jan 12 13:13:41 UTC 2023 x86_64

    
Build info:
    Compiler: /home/maxim-yurchuk/.ya/tools/v4/7451466407/bin/clang++
    Compiler version: 
        clang version 18.1.8
        Target: x86_64-unknown-linux-gnu
        Thread model: posix
        InstalledDir: /home/maxim-yurchuk/.ya/tools/v4/7451466407/bin
    Compile flags: -pipe -m64 -O3 -g -ggnu-pubnames -fdebug-info-for-profiling -fexceptions -fno-common -ffunction-sections -fdata-sections -fuse-init-array -fcolor-diagnostics -faligned-allocation -fdebug-default-version=4 -Wall -Wextra -Wno-parentheses -Wno-implicit-const-int-float-conversion -Wno-unknown-warning-option -Werror -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_YNDX_LIBUNWIND_ENABLE_EXCEPTION_BACKTRACE -D__LONG_LONG_SUPPORTED -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSSE3_ENABLED=1 -DSSE41_ENABLED=1 -DSSE42_ENABLED=1 -DPOPCNT_ENABLED=1 -DCX16_ENABLED=1 -fno-omit-frame-pointer -D_libunwind_ -DLIBCXX_BUILDING_LIBCXXRT -DNDEBUG -Wno-array-parameter -Wno-deprecate-lax-vec-conv-all -Wno-unqualified-std-cast-call -Wno-unused-but-set-parameter -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-function-pointer-types -Wno-address-of-packed-member -Wno-deprecated-this-capture -Wno-c++11-narrowing-const-reference -Wno-missing-field-initializers -Wno-packed-non-pod -Wno-format -Wno-vla-cxx-extension -Wno-invalid-offsetof -Wno-exceptions -Wno-include-angled-in-module-purview -Wno-unused-parameter -DCATBOOST_OPENSOURCE=yes -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mcx16 -DNDEBUG -Wno-array-parameter -Wno-deprecate-lax-vec-conv-all -Wno-unqualified-std-cast-call -Wno-unused-but-set-parameter -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-function-pointer-types -Wno-address-of-packed-member -Wno-deprecated-this-capture -Wno-c++11-narrowing-const-reference -Wno-missing-field-initializers -Wno-packed-non-pod -Wno-format -Wno-vla-cxx-extension -Wno-invalid-offsetof -Wno-exceptions -Wno-include-angled-in-module-purview -Wno-unused-parameter -std=c++20 -Wimport-preprocessor-directive-pedantic -Woverloaded-virtual -Wno-ambiguous-reversed-operator -Wno-defaulted-function-deleted -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-deprecated-enum-float-conversion -Wno-deprecated-volatile -Wno-pessimizing-move -Wno-undefined-var-template -nostdinc++ -DCATBOOST_OPENSOURCE=yes -nostdinc++
```

**Comment by maximyurchuk** [comment]
fixed by @ivanmorozov333
