### ISSUE TITLE
[coredump] #0 TIntrusivePtr<TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > >, TStringPtrOps<TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > > > >::Get

### ISSUE THREAD

**Issue by maximyurchuk** [ydb-platform/ydb#12324]
The coredump was found during TPC-H workload and some other loads. GDB output:
```
Core was generated by `/Berkanavt/kikimr/bin/kikimr server --yaml-config /Berkanavt/kikimr/cfg/config.'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  TIntrusivePtr<TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > >, TStringPtrOps<TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > > > >::Get (this=0x8) at /home/maxim-yurchuk/ydb/util/generic/ptr.h:579
579     /home/maxim-yurchuk/ydb/util/generic/ptr.h: No such file or directory.
[Current thread is 1 (Thread 0x7f2a142e6700 (LWP 1105655))]
#0  TIntrusivePtr<TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > >, TStringPtrOps<TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > > > >::Get (this=0x8) at /home/maxim-yurchuk/ydb/util/generic/ptr.h:579
#1  TPointerCommon<TIntrusivePtr<TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > >, TStringPtrOps<TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > > > >, TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > > >::AsT (this=0x8)
    at /home/maxim-yurchuk/ydb/util/generic/ptr.h:137
#2  TPointerBase<TIntrusivePtr<TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > >, TStringPtrOps<TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > > > >, TStdString<std::__y1::basic_string<char, std::__y1::char_traits<char>, std::__y1::allocator<char> > > >::operator* (this=0x8)
    at /home/maxim-yurchuk/ydb/util/generic/ptr.h:153
#3  TBasicString<char, std::__y1::char_traits<char> >::StdStr (this=0x8)
    at /home/maxim-yurchuk/ydb/util/generic/string.h:220
#4  TBasicString<char, std::__y1::char_traits<char> >::ConstRef (this=0x8)
    at /home/maxim-yurchuk/ydb/util/generic/string.h:242
#5  TBasicString<char, std::__y1::char_traits<char> >::data (this=0x8)
    at /home/maxim-yurchuk/ydb/util/generic/string.h:305
#6  TBasicStringBuf<char, std::__y1::char_traits<char> >::TBasicStringBuf<std::__y1::char_traits<char> > (this=0x7f2a142ac9d8, str=...)
    at /home/maxim-yurchuk/ydb/util/generic/strbuf.h:129
#7  TBasicString<char, std::__y1::char_traits<char> >::Join<char const*, TBasicString<char, std::__y1::char_traits<char> > > (r=<optimized out>, 
    r=<optimized out>) at /home/maxim-yurchuk/ydb/util/generic/string.h:618
#8  operator+ (s2=..., s1=<optimized out>)
    at /home/maxim-yurchuk/ydb/util/generic/string.h:989
#9  NKikimr::NOlap::NReader::NPlain::TFetchingScriptCursor::Execute (
    this=0x6e2d844edd0, source=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp:157
#10 0x00000000160fac31 in NKikimr::NOlap::NReader::NPlain::TStepAction::DoExecuteImpl (this=0x6e2d844ed98)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp:25
#11 0x000000001614c961 in NKikimr::NOlap::NReader::IDataTasksProcessor::ITask::DoExecute (this=0x1, taskPtr=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/common/conveyor_task.cpp:8
#12 0x00000000160b01e0 in NKikimr::NConveyor::ITask::Execute (
    this=0x6e2d844ed98, signals=..., taskPtr=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/conveyor/usage/abstract.cpp:13
#13 0x000000001cd7f24e in NKikimr::NConveyor::TWorker::ExecuteTask (this=
    0x6e2ffac32e0, workerTask=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/conveyor/service/worker.cpp:10
#14 0x000000000ef25c37 in NActors::TGenericExecutorThread::Execute (
    this=this@entry=0x6e2ff64d800, mailbox=mailbox@entry=0x6e2f85e13c0, 
    isTailExecution=<optimized out>)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:248
#15 0x000000000ef29401 in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*)::$_0::operator()(NActors::TMailbox*, bool) const (
    this=this@entry=0x7f2a142acf90, mailbox=mailbox@entry=0x6e2f85e13c0, 
    isTailExecution=false)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:425
#16 0x000000000ef28f53 in NActors::TGenericExecutorThread::ProcessExecutorPool
    (this=this@entry=0x6e2ff64d800, pool=<optimized out>)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:479
#17 0x000000000ef29b56 in NActors::TExecutorThread::ThreadProc (
    this=0x6e2ff64d800)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:510
#18 0x000000000e343898 in (anonymous namespace)::TPosixThread::ThreadProxy (
    arg=0x6e2fd007140) at /home/maxim-yurchuk/ydb/util/system/thread.cpp:244
#19 0x00007f2a31f15609 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#20 0x00007f2a31e35353 in clone () from /lib/x86_64-linux-gnu/libc.so.6

```

Found in:
On host ydb-sas-testing-0000.search.yandex.net, /coredumps/kikimr.User.1105515.11
On host ydb-sas-testing-0000.search.yandex.net, /coredumps/kikimr.User.1147343.11
On host ydb-sas-testing-0001.search.yandex.net, /coredumps/kikimr.User.3387691.11
On host ydb-sas-testing-0001.search.yandex.net, /coredumps/kikimr.User.3398977.11
On host ydb-sas-testing-0001.search.yandex.net, /coredumps/kikimr.User.3401005.11
On host ydb-sas-testing-0001.search.yandex.net, /coredumps/kikimr.User.3420007.11
On host ydb-sas-testing-0002.search.yandex.net, /coredumps/kikimr.User.3639657.11
On host ydb-sas-testing-0003.search.yandex.net, /coredumps/kikimr.User.428367.11
On host ydb-sas-testing-0003.search.yandex.net, /coredumps/kikimr.User.567517.11
On host ydb-sas-testing-0004.search.yandex.net, /coredumps/kikimr.User.3348475.11
On host ydb-sas-testing-0005.search.yandex.net, /coredumps/kikimr.User.3908947.11
On host ydb-sas-testing-0005.search.yandex.net, /coredumps/kikimr.User.3910615.11
On host ydb-sas-testing-0005.search.yandex.net, /coredumps/kikimr.User.3912071.11
On host ydb-sas-testing-0005.search.yandex.net, /coredumps/kikimr.User.3918783.11
On host ydb-sas-testing-0006.search.yandex.net, /coredumps/kikimr.User.2684274.11
On host ydb-sas-testing-0006.search.yandex.net, /coredumps/kikimr.User.2703739.11
On host ydb-sas-testing-0006.search.yandex.net, /coredumps/kikimr.User.2706071.11
On host ydb-sas-testing-0006.search.yandex.net, /coredumps/kikimr.User.2707917.11
On host ydb-sas-testing-0007.search.yandex.net, /coredumps/kikimr.User.2101384.11
On host ydb-sas-testing-0007.search.yandex.net, /coredumps/kikimr.User.2166369.11
On host ydb-sas-testing-0007.search.yandex.net, /coredumps/kikimr.User.2170196.11
On host ydb-sas-testing-0007.search.yandex.net, /coredumps/kikimr.User.2176319.11

```
maxim-yurchuk@ydb-sas-testing-0000:~$ /Berkanavt/kikimr/bin/kikimr -V
Git info:
    Commit: 73759b64031eccfc62243c58f9b086513e0e1509
    Branch: heads/main
    Author: Semyon <yentsovsemyon@ydb.tech>
    Summary: fix TTL initialization from DB on CS (#12210)

Other info:
    Build by: maxim-yurchuk
    Top src dir: /home/maxim-yurchuk/ydb
    Top build dir: /home/maxim-yurchuk/.ya/build
    Hostname: yurchuk-turbo.vla.yp-c.yandex.net
    Host information: 
        Linux yurchuk-turbo.vla.yp-c.yandex.net 5.4.210-39.1 #1 SMP Thu Jan 12 13:13:41 UTC 2023 x86_64

    
Build info:
    Compiler: /home/maxim-yurchuk/.ya/tools/v4/7451466407/bin/clang++
    Compiler version: 
        clang version 18.1.8
        Target: x86_64-unknown-linux-gnu
        Thread model: posix
        InstalledDir: /home/maxim-yurchuk/.ya/tools/v4/7451466407/bin
    Compile flags: -pipe -m64 -O3 -g -ggnu-pubnames -fdebug-info-for-profiling -fexceptions -fno-common -ffunction-sections -fdata-sections -fuse-init-array -fcolor-diagnostics -faligned-allocation -fdebug-default-version=4 -Wall -Wextra -Wno-parentheses -Wno-implicit-const-int-float-conversion -Wno-unknown-warning-option -Werror -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_YNDX_LIBUNWIND_ENABLE_EXCEPTION_BACKTRACE -D__LONG_LONG_SUPPORTED -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSSE3_ENABLED=1 -DSSE41_ENABLED=1 -DSSE42_ENABLED=1 -DPOPCNT_ENABLED=1 -DCX16_ENABLED=1 -fno-omit-frame-pointer -D_libunwind_ -DLIBCXX_BUILDING_LIBCXXRT -DNDEBUG -Wno-array-parameter -Wno-deprecate-lax-vec-conv-all -Wno-unqualified-std-cast-call -Wno-unused-but-set-parameter -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-function-pointer-types -Wno-address-of-packed-member -Wno-deprecated-this-capture -Wno-c++11-narrowing-const-reference -Wno-missing-field-initializers -Wno-packed-non-pod -Wno-format -Wno-vla-cxx-extension -Wno-invalid-offsetof -Wno-exceptions -Wno-include-angled-in-module-purview -Wno-unused-parameter -DCATBOOST_OPENSOURCE=yes -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mcx16 -DNDEBUG -Wno-array-parameter -Wno-deprecate-lax-vec-conv-all -Wno-unqualified-std-cast-call -Wno-unused-but-set-parameter -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-function-pointer-types -Wno-address-of-packed-member -Wno-deprecated-this-capture -Wno-c++11-narrowing-const-reference -Wno-missing-field-initializers -Wno-packed-non-pod -Wno-format -Wno-vla-cxx-extension -Wno-invalid-offsetof -Wno-exceptions -Wno-include-angled-in-module-purview -Wno-unused-parameter -std=c++20 -Wimport-preprocessor-directive-pedantic -Woverloaded-virtual -Wno-ambiguous-reversed-operator -Wno-defaulted-function-deleted -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-deprecated-enum-float-conversion -Wno-deprecated-volatile -Wno-pessimizing-move -Wno-undefined-var-template -nostdinc++ -DCATBOOST_OPENSOURCE=yes -nostdinc++
```

**Comment by maximyurchuk** [comment]
fixed by @ivanmorozov333
