### ISSUE TITLE
[coredump] #0 NKikimr::NOlap::NReader::NPlain::IFetchingStep::AddDataSize

### ISSUE THREAD

**Issue by maximyurchuk** [ydb-platform/ydb#12326]
The coredump was found during TPC-H workload and some other loads. GDB output:
```
Core was generated by `/Berkanavt/kikimr/bin/kikimr server --yaml-config /Berkanavt/kikimr/cfg/config.'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  NKikimr::NOlap::NReader::NPlain::IFetchingStep::AddDataSize (this=0x0, 
    size=0)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h:40
40      /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h: No such file or directory.
[Current thread is 1 (Thread 0x7ff091989700 (LWP 3416486))]
#0  NKikimr::NOlap::NReader::NPlain::IFetchingStep::AddDataSize (this=0x0, 
    size=0)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h:40
#1  NKikimr::NOlap::NReader::NPlain::TFetchingScript::AddStepDataSize (
    this=<optimized out>, index=<optimized out>, size=0)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h:79
#2  NKikimr::NOlap::NReader::NPlain::TFetchingScriptCursor::FlushDuration (
    this=0x4520895861c8)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h:138
#3  0x00000000160fde50 in NKikimr::NOlap::NReader::NPlain::TFetchingScriptCursor::Next (this=0x4520895861c8)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h:159
#4  NKikimr::NOlap::NReader::NPlain::TAllocateMemoryStep::TFetchingStepAllocation::DoOnAllocated (this=0x452089586198, guard=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp:189
#5  0x00000000160b0ab3 in NKikimr::NOlap::NGroupedMemoryManager::IAllocation::OnAllocated (this=0x452089586198, guard=..., allocation=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/usage/abstract.cpp:29
#6  0x000000001d6feba8 in NKikimr::NOlap::NGroupedMemoryManager::TAllocationInfo::Allocate (this=0x4520b8dc6c28, ownerId=...)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/allocation.h:57
#7  0x000000001d70658e in NKikimr::NOlap::NGroupedMemoryManager::TAllocationGroups::Allocate (this=0x45202e7db868, isPriorityProcess=true, process=..., 
    allocationsLimit=1)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/group.cpp:41
#8  0x000000001d6fb3ec in NKikimr::NOlap::NGroupedMemoryManager::TProcessMemoryScope::TryAllocateWaiting (this=0xe8640, allocationsCountLimit=1, 
    isPriorityProcess=<optimized out>)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/process.h:107
#9  NKikimr::NOlap::NGroupedMemoryManager::TProcessMemory::TryAllocateWaiting
    (this=0x45205b29f290, allocationsCountLimit=1)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/process.h:256
#10 NKikimr::NOlap::NGroupedMemoryManager::TManager::TryAllocateWaiting (
    this=this@entry=0x45203f840f88)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/manager.cpp:52
#11 0x000000001d6fb814 in NKikimr::NOlap::NGroupedMemoryManager::TManager::UnregisterAllocation (this=0x45203f840f88, externalProcessId=<optimized out>, 
    externalScopeId=95, allocationId=35043)
    at /home/maxim-yurchuk/ydb/ydb/core/tx/limiter/grouped_memory/service/manager.cpp:66
#12 0x000000000ef25c37 in NActors::TGenericExecutorThread::Execute (
    this=this@entry=0x45203f660400, mailbox=mailbox@entry=0x452038220a80, 
    isTailExecution=<optimized out>)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:248
#13 0x000000000ef29401 in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*)::$_0::operator()(NActors::TMailbox*, bool) const (
    this=this@entry=0x7ff09194ff90, mailbox=mailbox@entry=0x452038220a80, 
    isTailExecution=false)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:425
#14 0x000000000ef28f53 in NActors::TGenericExecutorThread::ProcessExecutorPool
    (this=this@entry=0x45203f660400, pool=<optimized out>)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:479
#15 0x000000000ef29b56 in NActors::TExecutorThread::ThreadProc (
    this=0x45203f660400)
    at /home/maxim-yurchuk/ydb/ydb/library/actors/core/executor_thread.cpp:510
#16 0x000000000e343898 in (anonymous namespace)::TPosixThread::ThreadProxy (
    arg=0x45203d089de0) at /home/maxim-yurchuk/ydb/util/system/thread.cpp:244
#17 0x00007ff0b15bc609 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#18 0x00007ff0b14dc353 in clone () from /lib/x86_64-linux-gnu/libc.so.6

```

Found in:
On host ydb-sas-testing-0001.search.yandex.net, /coredumps/kikimr.User.3416343.11
On host ydb-sas-testing-0002.search.yandex.net, /coredumps/kikimr.User.3558327.11
On host ydb-sas-testing-0002.search.yandex.net, /coredumps/kikimr.User.3596552.11
On host ydb-sas-testing-0002.search.yandex.net, /coredumps/kikimr.User.3614847.11
On host ydb-sas-testing-0002.search.yandex.net, /coredumps/kikimr.User.3648327.11
On host ydb-sas-testing-0003.search.yandex.net, /coredumps/kikimr.User.499027.11
On host ydb-sas-testing-0003.search.yandex.net, /coredumps/kikimr.User.527378.11
On host ydb-sas-testing-0003.search.yandex.net, /coredumps/kikimr.User.540768.11
On host ydb-sas-testing-0004.search.yandex.net, /coredumps/kikimr.User.3261974.11
On host ydb-sas-testing-0004.search.yandex.net, /coredumps/kikimr.User.3337153.11
On host ydb-sas-testing-0004.search.yandex.net, /coredumps/kikimr.User.3344085.11
On host ydb-sas-testing-0004.search.yandex.net, /coredumps/kikimr.User.3346999.11
On host ydb-sas-testing-0005.search.yandex.net, /coredumps/kikimr.User.3895789.11
On host ydb-sas-testing-0005.search.yandex.net, /coredumps/kikimr.User.3912769.11
On host ydb-sas-testing-0005.search.yandex.net, /coredumps/kikimr.User.3915251.11
On host ydb-sas-testing-0007.search.yandex.net, /coredumps/kikimr.User.2173916.11

```
maxim-yurchuk@ydb-sas-testing-0000:~$ /Berkanavt/kikimr/bin/kikimr -V
Git info:
    Commit: 73759b64031eccfc62243c58f9b086513e0e1509
    Branch: heads/main
    Author: Semyon <yentsovsemyon@ydb.tech>
    Summary: fix TTL initialization from DB on CS (#12210)

Other info:
    Build by: maxim-yurchuk
    Top src dir: /home/maxim-yurchuk/ydb
    Top build dir: /home/maxim-yurchuk/.ya/build
    Hostname: yurchuk-turbo.vla.yp-c.yandex.net
    Host information: 
        Linux yurchuk-turbo.vla.yp-c.yandex.net 5.4.210-39.1 #1 SMP Thu Jan 12 13:13:41 UTC 2023 x86_64

    
Build info:
    Compiler: /home/maxim-yurchuk/.ya/tools/v4/7451466407/bin/clang++
    Compiler version: 
        clang version 18.1.8
        Target: x86_64-unknown-linux-gnu
        Thread model: posix
        InstalledDir: /home/maxim-yurchuk/.ya/tools/v4/7451466407/bin
    Compile flags: -pipe -m64 -O3 -g -ggnu-pubnames -fdebug-info-for-profiling -fexceptions -fno-common -ffunction-sections -fdata-sections -fuse-init-array -fcolor-diagnostics -faligned-allocation -fdebug-default-version=4 -Wall -Wextra -Wno-parentheses -Wno-implicit-const-int-float-conversion -Wno-unknown-warning-option -Werror -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_YNDX_LIBUNWIND_ENABLE_EXCEPTION_BACKTRACE -D__LONG_LONG_SUPPORTED -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSSE3_ENABLED=1 -DSSE41_ENABLED=1 -DSSE42_ENABLED=1 -DPOPCNT_ENABLED=1 -DCX16_ENABLED=1 -fno-omit-frame-pointer -D_libunwind_ -DLIBCXX_BUILDING_LIBCXXRT -DNDEBUG -Wno-array-parameter -Wno-deprecate-lax-vec-conv-all -Wno-unqualified-std-cast-call -Wno-unused-but-set-parameter -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-function-pointer-types -Wno-address-of-packed-member -Wno-deprecated-this-capture -Wno-c++11-narrowing-const-reference -Wno-missing-field-initializers -Wno-packed-non-pod -Wno-format -Wno-vla-cxx-extension -Wno-invalid-offsetof -Wno-exceptions -Wno-include-angled-in-module-purview -Wno-unused-parameter -DCATBOOST_OPENSOURCE=yes -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mcx16 -DNDEBUG -Wno-array-parameter -Wno-deprecate-lax-vec-conv-all -Wno-unqualified-std-cast-call -Wno-unused-but-set-parameter -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-function-pointer-types -Wno-address-of-packed-member -Wno-deprecated-this-capture -Wno-c++11-narrowing-const-reference -Wno-missing-field-initializers -Wno-packed-non-pod -Wno-format -Wno-vla-cxx-extension -Wno-invalid-offsetof -Wno-exceptions -Wno-include-angled-in-module-purview -Wno-unused-parameter -std=c++20 -Wimport-preprocessor-directive-pedantic -Woverloaded-virtual -Wno-ambiguous-reversed-operator -Wno-defaulted-function-deleted -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-deprecated-enum-float-conversion -Wno-deprecated-volatile -Wno-pessimizing-move -Wno-undefined-var-template -nostdinc++ -DCATBOOST_OPENSOURCE=yes -nostdinc++
```

**Comment by maximyurchuk** [comment]
fixed by @ivanmorozov333
