### ISSUE TITLE
bug: CrashLoopBackOff after Storage creation

### ISSUE THREAD

**Issue by demoalex** [ydb-platform/ydb#23]
# Bug Report

**YDB Kubernetes Operator version:**

```
NAME        	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                        	APP VERSION
prom        	default  	1       	2022-04-20 22:49:30.209714 +0300 MSK	deployed	kube-prometheus-stack-34.10.0	0.55.0     
ydb-operator	default  	1       	2022-04-20 22:49:57.786045 +0300 MSK	deployed	operator-0.4.5               	0.4.9      
```

**Environment**

Minikube (MacOS 10.15.7), GKE, GKE autopilot

**Current behavior:**

This happens after any cluster setup based on 
https://ydb.tech/en/docs/getting_started/self_hosted/ydb_minikube
or
https://ydb.tech/en/docs/deploy/orchestrated/yc_managed_kubernetes

`panic: assignment to entry in nil map` after initial Storage setup 

`kubectl get storages.ydb.tech` shows always PENDING
<img width="561" alt="Screenshot 2022-04-21 at 11 58 53" src="https://user-images.githubusercontent.com/101798/164419312-0d21f47d-9f6d-4551-b71b-7125e994705a.png">

ydb-operator get into CrashLoopBackOff
<img width="704" alt="Screenshot 2022-04-21 at 11 59 10" src="https://user-images.githubusercontent.com/101798/164419352-8ecd88ac-0195-404d-af40-bb3f101e28c6.png">

**Steps to reproduce:**

follow this guide
https://ydb.tech/en/docs/getting_started/self_hosted/ydb_minikube

After storage create step

```
kubectl create -f - <<EOF
apiVersion: ydb.tech/v1alpha1
kind: Storage
metadata: 
  name: storage-sample
spec: 
  dataStore: 
    - 
      accessModes: 
        - ReadWriteOnce
      resources: 
        requests: 
          storage: 10Gi
      volumeMode: Block
  erasure: none
  nodes: 4
  version: "21.4.30"
EOF
```

**Related code:**

Full error code
```
panic: assignment to entry in nil map

goroutine 361 [running]:
github.com/ydb-platform/ydb-kubernetes-operator/internal/configuration.Build(0xc0005234c8, 0xc0005234c8)
	/workspace/internal/configuration/configuration.go:76 +0xea
github.com/ydb-platform/ydb-kubernetes-operator/internal/resources.(*StorageClusterBuilder).GetResourceBuilders(0xc0000b2498)
	/workspace/internal/resources/storage.go:59 +0xd9
github.com/ydb-platform/ydb-kubernetes-operator/internal/controllers/storage.(*StorageReconciler).handleResourcesSync(0xc0000b9810, {0x19c3838, 0xc000996e70}, 0xc0000b2498)
	/workspace/internal/controllers/storage/sync.go:168 +0x7a
github.com/ydb-platform/ydb-kubernetes-operator/internal/controllers/storage.(*StorageReconciler).Sync(0xc0000b94f0, {0x19c3838, 0xc000996e70}, 0xc000250879)
	/workspace/internal/controllers/storage/sync.go:69 +0xc5
github.com/ydb-platform/ydb-kubernetes-operator/internal/controllers/storage.(*StorageReconciler).Reconcile(0xc0000b9810, {0x19c3838, 0xc000996e70}, {{{0xc000250879, 0x1682520}, {0xc000250860, 0xc0002a7300}}})
	/workspace/internal/controllers/storage/controller.go:64 +0x1eb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00024d680, {0x19c3838, 0xc000996de0}, {{{0xc000250879, 0x1682520}, {0xc000250860, 0xc0004bc8c0}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:114 +0x222
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00024d680, {0x19c3790, 0xc0005bdd80}, {0x1608f40, 0xc00097a020})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:311 +0x2f2
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00024d680, {0x19c3790, 0xc0005bdd80})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:223 +0x354
```
<img width="583" alt="Screenshot 2022-04-21 at 11 58 00" src="https://user-images.githubusercontent.com/101798/164419152-a44f960c-2805-4b3c-ba67-491e8d4d0918.png">

<img width="1638" alt="Screenshot 2022-04-21 at 11 59 57" src="https://user-images.githubusercontent.com/101798/164419491-ecc78049-19c6-4d44-b23f-498beb555832.png">

**Comment by mvgorbunov** [comment]
We've update documentation - try to use configs examples for [minicube](https://github.com/ydb-platform/ydb-kubernetes-operator/tree/master/samples/minikube) and [managed k8s](https://github.com/ydb-platform/ydb-kubernetes-operator/blob/master/samples).
We will also add configs validation in operator, thanks for your report.
