### ISSUE TITLE
NYql::TPgBuilderImpl::MakeText unaligned access

### ISSUE THREAD

**Issue by qrort** [ydb-platform/ydb#2493]
```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/parser/pg_wrapper/utils.h:76:12 in 
/home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/parser/pg_wrapper/utils.h:76:12: runtime error: load of misaligned address 0x7fee9032b0a5 for type 'uint32' (aka 'unsigned int'), which requires 4 byte alignment
0x7fee9032b0a5: note: pointer points here
 00 00 00 00 44 00 00  00 4e 6f 72 74 68 20 4d  69 64 77 65 73 74 00 00  00 00 00 00 00 00 44 00  00
             ^ 
    #0 0x88681047 in NYql::GetFullVarSize(varlena const*) /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/parser/pg_wrapper/utils.h:76:12
    #1 0x888be9fe in NYql::TPgBuilderImpl::MakeText(char const*) const /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/parser/pg_wrapper/comp_factory.cpp:4172:20
    #2 0x6403ad40 in NKikimr::NMiniKQL::(anonymous namespace)::TStringBlockItemConverter<arrow::BinaryType, true, (NYql::NUdf::EPgStringType)1>::MakeValue(NYql::NUdf::TBlockItem, NKikimr::NMiniKQL::THolderFactory const&) const /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/minikql/computation/mkql_block_reader.cpp:63:32
    #3 0x63fbdf50 in NKikimr::NMiniKQL::(anonymous namespace)::TWideFromBlocksWrapper::TState::Get(NKikimr::NMiniKQL::THolderFactory const&, unsigned long) const /home/ee8jsmrbc5d1utc9advj/.ya/build/build_root/2dnn/0027f6/ydb/library/yql/minikql/comp_nodes/llvm14/mkql_blocks.cpp:697:38
    #4 0x63fbb851 in NKikimr::NMiniKQL::(anonymous namespace)::TWideFromBlocksWrapper::DoCalculate(NYql::NUdf::TUnboxedValue&, NKikimr::NMiniKQL::TComputationContext&, NYql::NUdf::TUnboxedValue* const*) const /home/ee8jsmrbc5d1utc9advj/.ya/build/build_root/2dnn/0027f6/ydb/library/yql/minikql/comp_nodes/llvm14/mkql_blocks.cpp:519:26
    #5 0x63fb9c3d in NKikimr::NMiniKQL::TStatefulWideFlowComputationNode<NKikimr::NMiniKQL::(anonymous namespace)::TWideFromBlocksWrapper, false>::FetchValues(NKikimr::NMiniKQL::TComputationContext&, NYql::NUdf::TUnboxedValue* const*) const /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/minikql/computation/mkql_computation_node_impl.h:653:52
    #6 0x659e92ed in NKikimr::NMiniKQL::(anonymous namespace)::TFromWideFlowWrapper::TStreamValue::WideFetch(NYql::NUdf::TUnboxedValue*, unsigned int) /home/ee8jsmrbc5d1utc9advj/.ya/build/build_root/2dnn/00280f/ydb/library/yql/minikql/comp_nodes/llvm14/mkql_flow.cpp:397:51
    #7 0x63fff884 in NYql::NUdf::TBoxedValueAccessor::WideFetch(NYql::NUdf::IBoxedValue&, NYql::NUdf::TUnboxedValue*, unsigned int) /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/public/udf/udf_value_inl.h:282:18
    #8 0x63fff4a6 in NYql::NUdf::TUnboxedValuePod::WideFetch(NYql::NUdf::TUnboxedValue*, unsigned int) const /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/public/udf/udf_value_inl.h:614:12
    #9 0x7b4a04b3 in NYql::NDq::TDqTaskRunner::FetchAndDispatch() /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/dq/runtime/dq_tasks_runner.cpp:894:61
    #10 0x7b41e235 in NYql::NDq::TDqTaskRunner::Run() /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/dq/runtime/dq_tasks_runner.cpp:712:26
    #11 0x7b6f4f11 in NYql::NDq::NTaskRunnerActor::TLocalTaskRunnerActor::OnContinueRun(TAutoPtr<NActors::TEventHandle<NYql::NDq::NTaskRunnerActor::TEvContinueRun>, TDelete>&) /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/dq/actors/task_runner/task_runner_actor_local.cpp:168:31
    #12 0x7b6ee522 in NYql::NDq::NTaskRunnerActor::TLocalTaskRunnerActor::Handler(TAutoPtr<NActors::IEventHandle, TDelete>&) /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/yql/dq/actors/task_runner/task_runner_actor_local.cpp:61:17
    #13 0x491fc201 in NActors::TActorCallbackBehaviour::Receive(NActors::IActor*, TAutoPtr<NActors::IEventHandle, TDelete>&) /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/actors/core/actor.cpp:232:9
    #14 0x495f6585 in NActors::IActor::Receive(TAutoPtr<NActors::IEventHandle, TDelete>&) /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/actors/core/actor.h:526:23
    #15 0x495d62eb in NActors::TGenericExecutorThread::TProcessingResult NActors::TGenericExecutorThread::Execute<NActors::TMailboxTable::THTSwapMailbox>(NActors::TMailboxTable::THTSwapMailbox*, unsigned int, bool) /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/actors/core/executor_thread.cpp:244:28
    #16 0x495acdc4 in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*)::$_0::operator()(unsigned int, bool) const /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/actors/core/executor_thread.cpp:425:25
    #17 0x495ab35f in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*) /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/actors/core/executor_thread.cpp:478:13
    #18 0x495af3ee in NActors::TExecutorThread::ThreadProc() /home/ee8jsmrbc5d1utc9advj/ydb/ydb/library/actors/core/executor_thread.cpp:504:9
    #19 0x47a05941 in void* (anonymous namespace)::ThreadProcWrapper<ISimpleThread>(void*) /home/ee8jsmrbc5d1utc9advj/ydb/util/system/thread.cpp:383:45
    #20 0x47a16050 in (anonymous namespace)::TPosixThread::ThreadProxy(void*) /home/ee8jsmrbc5d1utc9advj/ydb/util/system/thread.cpp:244:20
    #21 0x7feeede13608 in start_thread /build/glibc-wuryBv/glibc-2.31/nptl/pthread_create.c:477:8
    #22 0x7feeedd33352 in clone /build/glibc-wuryBv/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by qrort** [comment]
repro here: https://github.com/ydb-platform/ydb/issues/2279

**Comment by vitstn** [comment]
https://github.com/ydb-platform/ydb/pull/2545

**Comment by vitstn** [comment]
https://github.com/ydb-platform/ydb/pull/2524
