### ISSUE TITLE
[pg] Support binary format result

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb#3997]
Wire request from xorm:
```
Frame 612921: 210 bytes on wire (1680 bits), 210 bytes captured (1680 bits) on interface sshdump, id 0
Linux cooked capture v2
Internet Protocol Version 6, Src: ::1, Dst: ::1
Transmission Control Protocol, Src Port: 41344, Dst Port: 5432, Seq: 1105, Ack: 115382, Len: 118
PostgreSQL
    Type: Parse
    Length: 105
    Statement: 
    Query: INSERT INTO server_lock (operation_uid, last_execution, version) VALUES ($1, $2, $3) RETURNING id
    Parameters: 0
PostgreSQL
    Type: Describe
    Length: 6
    Statement: 
PostgreSQL
    Type: Sync
    Length: 4

...

Frame 613361: 163 bytes on wire (1304 bits), 163 bytes captured (1304 bits) on interface sshdump, id 0
Linux cooked capture v2
Internet Protocol Version 6, Src: ::1, Dst: ::1
Transmission Control Protocol, Src Port: 41344, Dst Port: 5432, Seq: 1223, Ack: 115440, Len: 71
PostgreSQL
    Type: Bind
    Length: 55
    Portal: 
    Statement: 
    Parameter formats: 0
    Parameter values: 3
        Column length: 18
        Data: 616c657274696e67206d6967726174696f6e
        Column length: 10
        Data: 31373133373931313431
        Column length: 1
        Data: 30
    Result formats: 1
        Format: Binary (1)
PostgreSQL
    Type: Execute
    Length: 9
    Portal: 
    Returns: all rows
PostgreSQL
    Type: Sync
    Length: 4
```

YDB Response:
```
Frame 613600: 123 bytes on wire (984 bits), 123 bytes captured (984 bits) on interface sshdump, id 0
Linux cooked capture v2
Internet Protocol Version 6, Src: ::1, Dst: ::1
Transmission Control Protocol, Src Port: 5432, Dst Port: 41344, Seq: 115445, Ack: 1294, Len: 31
PostgreSQL
    Type: Data row
    Length: 12
    Field count: 1
        Column length: 2
        Data: 3131
PostgreSQL
    Type: Command completion
    Length: 11
    Tag: INSERT
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: In a transaction (84)
```

PG 14 response:
```
Frame 1195: 134 bytes on wire (1072 bits), 134 bytes captured (1072 bits) on interface sshdump, id 0
Linux cooked capture v2
Internet Protocol Version 6, Src: ::1, Dst: ::1
Transmission Control Protocol, Src Port: 5433, Dst Port: 56256, Seq: 113196, Ack: 1284, Len: 42
PostgreSQL
    Type: Bind completion
    Length: 4
PostgreSQL
    Type: Data row
    Length: 14
    Field count: 1
        Column length: 4
        Data: 00000004
PostgreSQL
    Type: Command completion
    Length: 15
    Tag: INSERT 0 1
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: In a transaction (84)
```

Client failed while decode int from our text response
<details><summary>Stacktrace</summary>
```
runtime error: index out of range [3] with length 2" stackTrace="goroutine 1 [running]:
runtime/debug.Stack()
    runtime/debug/stack.go:24 +0x5e
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer.func2()
    github.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:98 +0x85
panic({0x103eac0?, 0xc002ba0c60?})
    runtime/panic.go:914 +0x21f
github.com/lib/pq.(*conn).errRecover(0xc002811500, 0xc002c9daf0)
    github.com/lib/pq@v1.10.9/error.go:493 +0x445
panic({0x103eac0?, 0xc002ba0c60?})
    runtime/panic.go:914 +0x21f
encoding/binary.bigEndian.Uint32(...)
    encoding/binary/binary.go:157
github.com/lib/pq.binaryDecode(0x0?, {0xc002811526?, 0x6b416c0?, 0xc002811798?}, 0x2a3a380?)
    github.com/lib/pq@v1.10.9/encode.go:79 +0x171
github.com/lib/pq.decode(0xc002811500?, {0xc002811526?, 0xc002c9daf8?, 0x5629045?}, 0x305bbf0?, 0x30?)
    github.com/lib/pq@v1.10.9/encode.go:64 +0x25
github.com/lib/pq.(*rows).Next(0xc002a3a320, {0xc0027ce2c0, 0x1, 0xc002c9dc90?})
    github.com/lib/pq@v1.10.9/conn.go:1618 +0x726
database/sql.(*Rows).nextLocked(0xc0027a8cf0)
    database/sql/sql.go:3019 +0x107
database/sql.(*Rows).Next.func1()
    database/sql/sql.go:2994 +0x29
database/sql.withLock({0x21cae58, 0xc0027a8d28}, 0xc002c9dc70)
    database/sql/sql.go:3502 +0x82
database/sql.(*Rows).Next(0xc0027a8cf0)
    database/sql/sql.go:2993 +0x85
xorm.io/xorm.(*Session).nocacheGet(0x100c002c9de90?, 0x6, 0x7efe776643c8?, {0x49b9e0?, 0xc003284048}, {0xc0032800c0?, 0x0?}, {0xc0032960c0, 0x3, 0x3})
    xorm.io/xorm@v0.8.2/session_get.go:79 +0xef
xorm.io/xorm.(*Session).get(0xc003060a80, {0x49b9e0, 0xc003284048?})
    xorm.io/xorm@v0.8.2/session_get.go:64 +0x394
xorm.io/xorm.(*Session).Get(0x662660a5?, {0x49b9e0?, 0xc003284048?})
    xorm.io/xorm@v0.8.2/session_get.go:21 +0x6f
github.com/grafana/grafana/pkg/infra/serverlock.(*ServerLockService).createLock(0xc0023a2a20, {0x2202550, 0xc00305b6e0}, 0xc002c9e160, 0xc00305b860)
    github.com/grafana/grafana/pkg/infra/serverlock/serverlock.go:351 +0x1e5
github.com/grafana/grafana/pkg/infra/serverlock.(*ServerLockService).acquireForRelease.func1(0xc00305b860)
    github.com/grafana/grafana/pkg/infra/serverlock/serverlock.go:287 +0x696
github.com/grafana/grafana/pkg/services/sqlstore.(*SQLStore).inTransactionWithRetryCtx(0xc002a3bea0, {0x2202550, 0xc00305b6e0}, 0xc002c9e2f8?, {0x21cacf8?, 0xc002a54510?}, 0xc0024de580, 0x0)
    github.com/grafana/grafana/pkg/services/sqlstore/transactions.go:56 +0x137
github.com/grafana/grafana/pkg/services/sqlstore.(*SQLStore).WithTransactionalDbSession(0x829fe0?, {0x2202550?, 0xc00305b6e0?}, 0x1555b75?)
    github.com/grafana/grafana/pkg/services/sqlstore/transactions.go:20 +0x32
github.com/grafana/grafana/pkg/infra/serverlock.(*ServerLockService).acquireForRelease(0xc0023a2a20, {0x2202550?, 0xc00305b680?}, {0x14d49f4, 0x12}, 0x8bb2c97000)
    github.com/grafana/grafana/pkg/infra/serverlock/serverlock.go:241 +0x182
github.com/grafana/grafana/pkg/infra/serverlock.(*ServerLockService).LockExecuteAndRelease(0xc0023a2a20, {0x22022b0, 0xa4cf080}, {0x14d49f4, 0x12}, 0x1c0?, 0xc0000e4800?)
    github.com/grafana/grafana/pkg/infra/serverlock/serverlock.go:146 +0x3b0
github.com/grafana/grafana/pkg/services/ngalert/migration.(*migrationService).Run(0xc003018b60, {0x22022b0, 0xa4cf080})
    github.com/grafana/grafana/pkg/services/ngalert/migration/service.go:354 +0x85
github.com/grafana/grafana/pkg/services/ngalert.ProvideService(_, {_, _}, {_, _}, {_, _}, {_, _}, {0x2230348, ...}, ...)
    github.com/grafana/grafana/pkg/services/ngalert/ngalert.go:111 +0x58c
github.com/grafana/grafana/pkg/server.Initialize(0xc002858000, {{0x0, 0x0}, {0x0, 0x0}, {0x219d658, 0x6}, {0x21e6d80, 0x28}, {0x219eb58, ...}, ...}, ...)
    github.com/grafana/grafana/pkg/server/wire_gen.go:523 +0x5145
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x219d658, 0x6}, {0x21e6d80, 0x28}, {0x148fdf9, 0x2}, {0x219eb58, 0x7}, {0x0, 0x0}, ...})
    github.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:119 +0x765
main.main.ServerCommand.func2(0xc00233fa30?)
    github.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:44 +0xf8
github.com/urfave/cli/v2.(*Command).Run(0xc0028249a0, 0xc0028423c0, {0xc00268afc0, 0x9, 0x9})
    github.com/urfave/cli/v2@v2.25.0/command.go:273 +0x998
github.com/urfave/cli/v2.(*Command).Run(0xc002825080, 0xc002842280, {0xc0001c1360, 0xa, 0xa})
    github.com/urfave/cli/v2@v2.25.0/command.go:266 +0xbe5
github.com/urfave/cli/v2.(*App).RunContext(0xc0001e23c0, {0x22022b0?, 0xa4cf080}, {0xc0001c1360, 0xa, 0xa})
    github.com/urfave/cli/v2@v2.25.0/app.go:332 +0x5b7
github.com/urfave/cli/v2.(*App).Run(...)
    github.com/urfave/cli/v2@v2.25.0/app.go:309
main.main()
    github.com/grafana/grafana/pkg/cmd/grafana/main.go:54 +0xb2b
"

grafana  | panic: runtime error: index out of range [3] with length 2 [recovered]
grafana  |      panic: runtime error: index out of range [3] with length 2 [recovered]
grafana  |      panic: runtime error: index out of range [3] with length 2
```
</details>

**Comment by rekby** [comment]
@qrort 

At grafana startup for query: "INSERT INTO server_lock (operation_uid, last_execution, version) VALUES ($1, $2, $3) RETURNING id"

<details><summary>Binded parameters</summary>
```
Frame 334: 163 bytes on wire (1304 bits), 163 bytes captured (1304 bits) on interface sshdump, id 0
Linux cooked capture v2
Internet Protocol Version 6, Src: ::1, Dst: ::1
Transmission Control Protocol, Src Port: 42276, Dst Port: 5432, Seq: 1223, Ack: 115440, Len: 71
PostgreSQL
    Type: Bind
    Length: 55
    Portal: 
    Statement: 
    Parameter formats: 0
    Parameter values: 3
        Column length: 18
        Data: 616c657274696e67206d6967726174696f6e
        Column length: 10
        Data: 31373135373733373739
        Column length: 1
        Data: 30
    Result formats: 1
        Format: Binary (1)
PostgreSQL
    Type: Execute
    Length: 9
    Portal: 
    Returns: all rows
PostgreSQL
    Type: Sync
    Length: 4
```
</details> 

tcpdump of ydb and native postgres in attachements.
[postgres-tcpdump.pcap.gz](https://github.com/ydb-platform/ydb/files/15321124/postgres-tcpdump.pcap.gz)
[ydb-tcpdump.pcap.gz](https://github.com/ydb-platform/ydb/files/15321126/ydb-tcpdump.pcap.gz)
