### ISSUE TITLE
ydbd crashed on within tcmalloc::tcmalloc_internal::Span::IdxToPtrSized

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb#7180]
```
#0  0x000000001b1239d5 in tcmalloc::tcmalloc_internal::Span::IdxToPtrSized<(tcmalloc::tcmalloc_internal::Span::Align)0> (this=0x553a5f173cf0, idx=2304, size=512)
    at /home/rekby/ydbwork/ydb/contrib/libs/tcmalloc/tcmalloc/span.h:332
#1  tcmalloc::tcmalloc_internal::Span::FreelistPopBatchSized<(tcmalloc::tcmalloc_internal::Span::Align)0> (this=0x553a5f173cf0, batch=0x7f3f576b3310, N=32, size=512)
    at /home/rekby/ydbwork/ydb/contrib/libs/tcmalloc/tcmalloc/span.h:389
#2  0x000000001b100060 in tcmalloc::tcmalloc_internal::CentralFreeList::RemoveRange (this=0x1c199f08 <tcmalloc::tcmalloc_internal::Static::transfer_cache_+4360>, batch=0x7f3f576b3310, N=32)
    at /home/rekby/ydbwork/ydb/contrib/libs/tcmalloc/tcmalloc/central_freelist.cc:151
#3  0x000000001b106de7 in tcmalloc::tcmalloc_internal::internal_transfer_cache::RingBufferTransferCache<tcmalloc::tcmalloc_internal::CentralFreeList, tcmalloc::tcmalloc_internal::TransferCacheManager>::RemoveRange (this=<optimized out>, size_class=<optimized out>, batch=0x7f3f576b3310, N=32) at /home/rekby/ydbwork/ydb/contrib/libs/tcmalloc/tcmalloc/transfer_cache_internals.h:592
#4  0x000000001b12a2c8 in tcmalloc::tcmalloc_internal::TransferCacheManager::RemoveRange (this=0x553adcf80000, size_class=-587708416, batch=0x7f3f576b3310, n=2304)
    at /home/rekby/ydbwork/ydb/contrib/libs/tcmalloc/tcmalloc/transfer_cache.h:209
#5  tcmalloc::tcmalloc_internal::ThreadCache::FetchFromCentralCache (this=0x55373f465680, cl=93711303723008, byte_size=512) at /home/rekby/ydbwork/ydb/contrib/libs/tcmalloc/tcmalloc/thread_cache.cc:83
#6  0x000000001b0ff09e in tcmalloc::tcmalloc_internal::ThreadCache::AllocateSlow<&tcmalloc::tcmalloc_internal::TCMallocPolicy<tcmalloc::tcmalloc_internal::CppOomPolicy, tcmalloc::tcmalloc_internal::DefaultAlignPolicy, tcmalloc::tcmalloc_internal::InvokeHooksPolicy, tcmalloc::tcmalloc_internal::LocalNumaPartitionPolicy>::handle_oom> (this=0x553a5f173cf0, cl=93711303723008, cl@entry=22,
    allocated_size=512) at /home/rekby/ydbwork/ydb/contrib/libs/tcmalloc/tcmalloc/thread_cache.h:101
#7  0x000000001b0f9e8b in tcmalloc::tcmalloc_internal::ThreadCache::Allocate<&tcmalloc::tcmalloc_internal::TCMallocPolicy<tcmalloc::tcmalloc_internal::CppOomPolicy, tcmalloc::tcmalloc_internal::DefaultAlignPolicy, tcmalloc::tcmalloc_internal::InvokeHooksPolicy, tcmalloc::tcmalloc_internal::LocalNumaPartitionPolicy>::handle_oom> (this=0x553adcf80000, cl=22)
    at /home/rekby/ydbwork/ydb/contrib/libs/tcmalloc/tcmalloc/thread_cache.h:301
```

git commit: db92b742b319ed85392c8c1cb85a636718ce1f71

I have binary, logs and full coredump of the crash, but havn't reproduce scenario.
It is a very big log and I have no space on the disk. May be it is a trigger of the problem

**Comment by rekby** [comment]
I have no space on my computer
