### ISSUE TITLE
CS fails on 24-3-4

### ISSUE THREAD

**Issue by zverevgeny** [ydb-platform/ydb#7468]
Aug  5 16:33:59 ydb-ru-prestable-sas-0000 kikimr_31003[2322897]: VERIFY failed (2024-08-05T16:33:59.641861+0300): tablet_id=72075186528083690;event=initialize_shard;verification=!GCBarrierPreparation.Generation() || LastCollectedGenStep <= GCBarrierPreparation;fline=blob_manager.cpp:146;prepared=19167:0;last=19184:0;

#0  0x00007f96eaa1e00b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f96ea9fd859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x000055c0cec8f207 in NPrivate::InternalPanicImpl(int, char const*, char const*, int, int, int, TBasicStringBuf<char, std::__y1::char_traits<char> >, char const*, unsigned long) ()
#3  0x000055c0cec8701c in NPrivate::Panic(NPrivate::TStaticBuf const&, int, char const*, char const*, char const*, ...) ()
#4  0x000055c0cf23af68 in NActors::TVerifyFormattedRecordWriter::~TVerifyFormattedRecordWriter() ()
#5  0x000055c0da23ee92 in NKikimr::NOlap::TBlobManager::LoadState(NKikimr::NOlap::IBlobManagerDb&, NKikimr::NOlap::TTabletId) ()
#6  0x000055c0d8996536 in NKikimr::NOlap::IStoragesManager::LoadIdempotency(NKikimr::NTable::TDatabase&) ()
#7  0x000055c0da0fa6d3 in NKikimr::NColumnShard::TTxInit::ReadEverything(NKikimr::NTabletFlatExecutor::TTransactionContext&, NActors::TActorContext const&) ()
#8  0x000055c0da0fcf16 in NKikimr::NColumnShard::TTxInit::Execute(NKikimr::NTabletFlatExecutor::TTransactionContext&, NActors::TActorContext const&) ()
#9  0x000055c0d2c578ba in NKikimr::NTabletFlatExecutor::TExecutor::ExecuteTransaction(TAutoPtr<NKikimr::NTabletFlatExecutor::TSeat, TDelete>, NActors::TActorContext const&) ()
#10 0x000055c0d2c67290 in NKikimr::NTabletFlatExecutor::TExecutor::Handle(TAutoPtr<NActors::TEventHandle<NKikimr::NTabletFlatExecutor::TExecutor::TEvPrivate::TEvActivateExecution>, TDelete>&, NActors::TActorContext const&) ()
#11 0x000055c0d2c405ad in NKikimr::NTabletFlatExecutor::TExecutor::StateWork(TAutoPtr<NActors::IEventHandle, TDelete>&) ()
#12 0x000055c0cf21d1e7 in NActors::TGenericExecutorThread::TProcessingResult NActors::TGenericExecutorThread::Execute<NActors::TMailboxTable::TReadAsFilledMailbox>(NActors::TMailboxTable::TReadAsFilledMailbox*, unsigned int, bool) ()
#13 0x000055c0cf20fd7f in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*)::$_0::operator()(unsigned int, bool) const ()
#14 0x000055c0cf20f5c0 in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*) ()
#15 0x000055c0cf2109a5 in NActors::TExecutorThread::ThreadProc() ()
#16 0x000055c0cec951fa in (anonymous namespace)::TPosixThread::ThreadProxy(void*) ()

**Comment by zverevgeny** [comment]
The problem was introduced in the previous 24-3-x rollout, which was build from partially implemented optimization. That build wrote incorrect state to local DB.
Fix: Ignore incorrect state, optimization will not work. Incorrect state will be overwritten by proper state later on by the process
