### ISSUE TITLE
"OSError: [Errno 5] Input/output error" on startup

### ISSUE THREAD

**Issue by OSA413** [ydb-platform/ydb#75]
Edit: смотрите ниже в комментариях

<details>
 <summary>Docker Compose Logs</summary>

```
Traceback (most recent call last):
  File "contrib/tools/python3/src/Lib/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "contrib/tools/python3/src/Lib/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "ydb/public/tools/local_ydb/__main__.py", line 140, in <module>
    arguments.command(arguments)
  File "ydb/public/tools/lib/cmds/__init__.py", line 298, in deploy
    cluster.start()
  File "ydb/tests/library/harness/kikimr_runner.py", line 272, in start
    self.__run()
  File "ydb/tests/library/harness/kikimr_runner.py", line 290, in __run
    self.__run_node(node_id)
  File "ydb/tests/library/harness/kikimr_runner.py", line 321, in __run_node
    self.__format_disks(node_id)
  File "ydb/tests/library/harness/kikimr_runner.py", line 431, in __format_disks
    self.nodes[node_id].format_pdisk(**pdisk)
  File "ydb/tests/library/harness/kikimr_runner.py", line 112, in format_pdisk
    out.write(b'\0')
OSError: [Errno 5] Input/output error
```

</details>

**Comment by OSA413** [comment]
Upd: эта ошибка не возникает, если запускать с помощью `docker`, а не `docker-compose`

**Comment by OSA413** [comment]
Если запустить БД как написано в примере, то всё работает, но почему-то создаются папки с `;C` на конце.
Windows 10
![image](https://user-images.githubusercontent.com/16105352/174640166-926af05a-57d5-4d77-b4a8-c4d29e4a9414.png)

**Comment by OSA413** [comment]
Я попробовал запустить докер из CMD, но там такая же ошибка, что при запуске из Docker Compose (`OSError: [Errno 5] Input/output error` при запуске).
