### ISSUE TITLE
Fix Verify in THeap::RecoveryModeAllocate

### ISSUE THREAD

**Issue by fexolm** [ydb-platform/ydb#7670]
```
#0  0x00007fc9f37ffc37 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fc9f3803028 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x000000000dabe3f2 in NPrivate::InternalPanicImpl(int, char const*, char const*, int, int, int, TBasicStringBuf<char, std::__y1::char_traits<char> >, char const*, unsigned long) (line=line@entry=792, 
    function=function@entry=0xf47621 "RecoveryModeAllocate", expr=expr@entry=0x109c73f "it != FreeChunks.end()", file=..., 
    errorMessage=0x51ef9913e00 "VDISK[82000002:_:0:1:0]: addr# {ChunkIdx: 6 Offset: 1670304 Size: 1595781} State# FreeChunks: [] CHAINS: {ChunkSize# 135249920 AppendBlockSize# 4064 MinHugeBlobInBytes# 4064 MaxBlobInBytes# 10485760 {"..., errorMessageSize=6694) at /home/fexolm/git/ydb/util/system/yassert.cpp:90
#3  0x000000000dab95ec in NPrivate::Panic(NPrivate::TStaticBuf const&, int, char const*, char const*, char const*, ...) (file=..., line=line@entry=792, function=0xf47621 "RecoveryModeAllocate", 
    expr=0x109c73f "it != FreeChunks.end()", format=<optimized out>) at /home/fexolm/git/ydb/util/system/yassert.cpp:55
#4  0x0000000018b99222 in NKikimr::NHuge::THeap::RecoveryModeAllocate(NKikimr::TDiskPart const&) (this=0x51e80cab6b0, addr=...)
    at /home/fexolm/git/ydb/ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugeheap.cpp:792
#5  0x0000000018b90da0 in NKikimr::NHuge::THullHugeKeeperPersState::Apply(NActors::TActorContext const&, unsigned long, NKikimr::NHuge::TPutRecoveryLogRec const&) (this=0x51eaee84a78, ctx=..., 
    lsn=<optimized out>, rec=...) at /home/fexolm/git/ydb/ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugerecovery.cpp:478
#6  0x0000000018ba0361 in NKikimr::TRecoveryLogReplayer::HandleHugeLogoBlob(NActors::TActorContext const&, NKikimr::NPDisk::TLogRecord const&) (this=this@entry=0x51ebdbfa680, ctx=..., record=...)
    at /home/fexolm/git/ydb/ydb/core/blobstorage/vdisk/localrecovery/localrecovery_logreplay.cpp:669
#7  0x0000000018b9ef50 in NKikimr::TRecoveryLogReplayer::DispatchLogRecord(NActors::TActorContext const&, NKikimr::NPDisk::TLogRecord const&) (this=this@entry=0x51ebdbfa680, ctx=..., record=...)
    at /home/fexolm/git/ydb/ydb/core/blobstorage/vdisk/localrecovery/localrecovery_logreplay.cpp:861
#8  0x0000000018b9e4e8 in NKikimr::TRecoveryLogReplayer::InterruptableLogRecordsDispatch(NActors::TActorContext const&) (this=0x51ebdbfa680, ctx=...)
    at /home/fexolm/git/ydb/ydb/core/blobstorage/vdisk/localrecovery/localrecovery_logreplay.cpp:125
#9  0x0000000018b9e40b in NKikimr::TRecoveryLogReplayer::Handle(TAutoPtr<NActors::TEventHandle<NKikimr::NPDisk::TEvReadLogResult>, TDelete>&, NActors::TActorContext const&) (this=0xda45f, 
    this@entry=0x51ebdbfa680, ev=..., ctx=...) at /home/fexolm/git/ydb/ydb/core/blobstorage/vdisk/localrecovery/localrecovery_logreplay.cpp:118
#10 0x0000000018b9e111 in NKikimr::TRecoveryLogReplayer::StateFunc(TAutoPtr<NActors::IEventHandle, TDelete>&) (this=0x51ebdbfa680, ev=...)
    at /home/fexolm/git/ydb/ydb/core/blobstorage/vdisk/localrecovery/localrecovery_logreplay.cpp:917
#11 0x000000000e5f12b4 in NActors::TGenericExecutorThread::Execute<NActors::TMailboxTable::THTSwapMailbox>(NActors::TMailboxTable::THTSwapMailbox*, unsigned int, bool) (this=this@entry=0x51ebce4f180, 
    mailbox=0x51eb98c15c0, hint=hint@entry=87, isTailExecution=<optimized out>) at /home/fexolm/git/ydb/ydb/library/actors/core/executor_thread.cpp:251
#12 0x000000000e5e9742 in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*)::$_0::operator()(unsigned int, bool) const (this=this@entry=0x7fc9ecb10260, 
    activation=activation@entry=87, isTailExecution=false) at /home/fexolm/git/ydb/ydb/library/actors/core/executor_thread.cpp:439
#13 0x000000000e5e913a in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*) (this=this@entry=0x51ebce4f180, pool=<optimized out>)
    at /home/fexolm/git/ydb/ydb/library/actors/core/executor_thread.cpp:492
#14 0x000000000e5e9ed7 in NActors::TExecutorThread::ThreadProc() (this=0x51ebce4f180) at /home/fexolm/git/ydb/ydb/library/actors/core/executor_thread.cpp:523
#15 0x000000000dac262a in (anonymous namespace)::TPosixThread::ThreadProxy(void*) (arg=0x51ebd2b4320) at /home/fexolm/git/ydb/util/system/thread.cpp:244
#16 0x00007fc9f3d9d184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#17 0x00007fc9f38c703d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

This crash was caught on version 24.3.5 on unstable cluster with nemesis (which kills random nodes sometimes).

Workload is simple create / drop table with store = column

**Comment by alexvru** [comment]
Successful repo.
