### ISSUE TITLE
UB in TDqComputeActorBase::InitializeTask

### ISSUE THREAD

**Issue by sharpeye** [ydb-platform/ydb#8170]
`TDqComputeActorBase::InitializeTask` is being called from the constructor of `TDqComputeActorBase` and there's a code like this:
```cpp
static_cast<TDerived*>(this)->SomeFunction(...)
```
it's UB because `TDerived` is not initialized yet:
```
=== CheckClustersList. Subcribe to ClusterTracker from [1:7405775775187851438:12336] 
/actions-runner/_work/nbs/nbs/contrib/ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h:1663:21: runtime error: downcast of address 0x7fab88acba50 which does not point to an object of type 'NKikimr::NKqp::TKqpComputeActor'
0x7fab88acba50: note: object is of type 'NYql::NDq::TDqComputeActorBase<NKikimr::NKqp::TKqpComputeActor, NYql::NDq::TComputeActorAsyncInputHelperForTaskRunner>'
 00 00 00 00  a8 5f 1e 4d 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'NYql::NDq::TDqComputeActorBase<NKikimr::NKqp::TKqpComputeActor, NYql::NDq::TComputeActorAsyncInputHelperForTaskRunner>'
2024-08-22T01:52:24.768102Z node 1 :METADATA_PROVIDER ERROR: fline=table_exists.cpp:59;actor=TTableExistsActor;event=timeout;self_id=[1:7405775770892883326:4277];send_to=[0:7307199536658146131:7762515];
2024-08-22T01:52:24.768181Z node 1 :METADATA_PROVIDER ERROR: fline=accessor_snapshot_base.cpp:68;action=cannot detect path existence;path=//Root/.metadata/initialization/migrations;error=timeout;
...
warning: address range table at offset 0xd30 has a premature terminator entry at offset 0xd40
    #0 0x44b419d1 in NYql::NDq::TDqComputeActorBase<NKikimr::NKqp::TKqpComputeActor, NYql::NDq::TComputeActorAsyncInputHelperForTaskRunner>::InitializeTask() /actions-runner/_work/nbs/nbs/contrib/ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h:1663:21
    #1 0x44b3fbee in NYql::NDq::TDqComputeActorBase<NKikimr::NKqp::TKqpComputeActor, NYql::NDq::TComputeActorAsyncInputHelperForTaskRunner>::TDqComputeActorBase(NActors::TActorId const&, std::__y1::variant<unsigned long, TBasicString<char, std::__y1::char_traits<char>>> const&, NYql::NDqProto::TDqTask*, TIntrusivePtr<NYql::NDq::IDqAsyncIoFactory, TDefaultIntrusivePtrOps<NYql::NDq::IDqAsyncIoFactory>>, NKikimr::NMiniKQL::IFunctionRegistry const*, NYql::NDq::TComputeRuntimeSettings const&, NYql::NDq::TComputeMemoryLimits const&, bool, bool, TIntrusivePtr<NMonitoring::TDynamicCounters, TDefaultIntrusivePtrOps<NMonitoring::TDynamicCounters>> const&, NWilson::TTraceId, TIntrusivePtr<NActors::TProtoArenaHolder, TDefaultIntrusivePtrOps<NActors::TProtoArenaHolder>>) /actions-runner/_work/nbs/nbs/contrib/ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h:193:9
    #2 0x44b1fe39 in NYql::NDq::TDqSyncComputeActorBase<NKikimr::NKqp::TKqpComputeActor>::TDqComputeActorBase /actions-runner/_work/nbs/nbs/contrib/ydb/library/yql/dq/actors/compute/dq_sync_compute_actor_base.h:29:86
    #3 0x44b1fe39 in NKikimr::NKqp::TKqpComputeActor::TKqpComputeActor(NActors::TActorId const&, unsigned long, NYql::NDqProto::TDqTask*, TIntrusivePtr<NYql::NDq::IDqAsyncIoFactory, TDefaultIntrusivePtrOps<NYql::NDq::IDqAsyncIoFactory>>, NKikimr::NMiniKQL::IFunctionRegistry const*, NYql::NDq::TComputeRuntimeSettings const&, NYql::NDq::TComputeMemoryLimits const&, NWilson::TTraceId, TIntrusivePtr<NActors::TProtoArenaHolder, TDefaultIntrusivePtrOps<NActors::TProtoArenaHolder>>) /actions-runner/_work/nbs/nbs/contrib/ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp:18:7
    #4 0x44b2f0f8 in NKikimr::NKqp::CreateKqpComputeActor(NActors::TActorId const&, unsigned long, NYql::NDqProto::TDqTask*, TIntrusivePtr<NYql::NDq::IDqAsyncIoFactory, TDefaultIntrusivePtrOps<NYql::NDq::IDqAsyncIoFactory>>, NKikimr::NMiniKQL::IFunctionRegistry const*, NYql::NDq::TComputeRuntimeSettings const&, NYql::NDq::TComputeMemoryLimits const&, NWilson::TTraceId, TIntrusivePtr<NActors::TProtoArenaHolder, TDefaultIntrusivePtrOps<NActors::TProtoArenaHolder>>) /actions-runner/_work/nbs/nbs/contrib/ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp:278:16
    #5 0x46793e87 in NKikimr::NKqp::(anonymous namespace)::TKqpNodeService::HandleWork(TAutoPtr<NActors::TEventHandle<NKikimr::NKqp::TEvKqpNode::TEvStartKqpTasksRequest>, TDelete>&) /actions-runner/_work/nbs/nbs/contrib/ydb/core/kqp/node_service/kqp_node_service.cpp:493:36
    #6 0x22701181 in NActors::TGenericExecutorThread::TProcessingResult NActors::TGenericExecutorThread::Execute<NActors::TMailboxTable::THTSwapMailbox>(NActors::TMailboxTable::THTSwapMailbox*, unsigned int, bool) /actions-runner/_work/nbs/nbs/contrib/ydb/library/actors/core/executor_thread.cpp:251:28
    #7 0x226e9ecd in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*)::$_0::operator()(unsigned int, bool) const /actions-runner/_work/nbs/nbs/contrib/ydb/library/actors/core/executor_thread.cpp:439:25
    #8 0x226e8745 in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*) /actions-runner/_work/nbs/nbs/contrib/ydb/library/actors/core/executor_thread.cpp:492:13
    #9 0x226ec6b5 in NActors::TExecutorThread::ThreadProc() /actions-runner/_work/nbs/nbs/contrib/ydb/library/actors/core/executor_thread.cpp:523:9
    #10 0x206dfda4 in (anonymous namespace)::TPosixThread::ThreadProxy(void*) /actions-runner/_work/nbs/nbs/util/system/thread.cpp:244:20
    #11 0x7fabade5eac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
    #12 0x7fabadef084f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
```

In a nutshell: https://godbolt.org/z/fjvEKhesd

**Comment by sharpeye** [comment]
It's fixed already #3832
