### ISSUE TITLE
segfault in TViewerPipeClient::HandleResolveDatabase 

### ISSUE THREAD

**Issue by dorooleg** [ydb-platform/ydb#8345]
```
(gdb) bt
#0  NActors::IEventHandle::Get<NActors::NMon::TEvHttpInfo> (this=0x0) at /home/grigoriypisar/ydbwork/ydb/ydb/library/actors/core/event.h:97
#1  0x000055d047fb4fc9 in NActors::TEventHandle<NActors::NMon::TEvHttpInfo>::Get (this=0x0) at /home/grigoriypisar/ydbwork/ydb/ydb/library/actors/core/event.h:354
#2  NKikimr::NViewer::TViewerPipeClient::GetRequest (this=this@entry=0x56dc7ebe9400) at /home/grigoriypisar/ydbwork/ydb/ydb/core/viewer/json_pipe_req.cpp:545
#3  0x000055d047fb568a in NKikimr::NViewer::TViewerPipeClient::MakeForward (this=this@entry=0x56dc7ebe9400, nodes=...) at /home/grigoriypisar/ydbwork/ydb/ydb/core/viewer/json_pipe_req.cpp:589
#4  0x000055d047fb59a5 in NKikimr::NViewer::TViewerPipeClient::HandleResolveDatabase (this=0x56dc7ebe9400, ev=...) at /home/grigoriypisar/ydbwork/ydb/ydb/core/viewer/json_pipe_req.cpp:628
#5  0x000055d03b1ac7c2 in NActors::TGenericExecutorThread::Execute<NActors::TMailboxTable::THTSwapMailbox> (this=this@entry=0x56dc7e1a6d00, mailbox=0x56dc7a5fff00, hint=hint@entry=4092, isTailExecution=<optimized out>)
    at /home/grigoriypisar/ydbwork/ydb/ydb/library/actors/core/executor_thread.cpp:251
#6  0x000055d03b1a3e1b in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*)::$_0::operator()(unsigned int, bool) const (this=this@entry=0x7f7f0254ff68, activation=activation@entry=4092, isTailExecution=false)
    at /home/grigoriypisar/ydbwork/ydb/ydb/library/actors/core/executor_thread.cpp:440
#7  0x000055d03b1a3780 in NActors::TGenericExecutorThread::ProcessExecutorPool (this=this@entry=0x56dc7e1a6d00, pool=<optimized out>) at /home/grigoriypisar/ydbwork/ydb/ydb/library/actors/core/executor_thread.cpp:493
#8  0x000055d03b1a4677 in NActors::TExecutorThread::ThreadProc (this=0x56dc7e1a6d00) at /home/grigoriypisar/ydbwork/ydb/ydb/library/actors/core/executor_thread.cpp:524
#9  0x000055d03a4f7a6a in (anonymous namespace)::TPosixThread::ThreadProxy (arg=0x56dc7e3af6a0) at /home/grigoriypisar/ydbwork/ydb/util/system/thread.cpp:244
#10 0x00007f7f1c9b1609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007f7f1c8d1353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Event не существуте в момент вызова HandleResolveDatabase. Воспрозводится при удалении таблицы из embedded ui.

```
drop table t1
```

Последнее изменение в этом месте было в https://github.com/ydb-platform/ydb/pull/8111

**Comment by dorooleg** [comment]
KIKIMR-21914
