### ISSUE TITLE
KqpLimits::CancelAfterRoTxWithFollowerStreamLookupDepededRead failed on msan 

### ISSUE THREAD

**Issue by dcherednik** [ydb-platform/ydb#9212]
warning: address range table at offset 0xb80 has a premature terminator entry at offset 0xb90
warning: address range table at offset 0xca0 has a premature terminator entry at offset 0xcb0
warning: address range table at offset 0xcd0 has a premature terminator entry at offset 0xce0
warning: address range table at offset 0xd00 has a premature terminator entry at offset 0xd10
warning: address range table at offset 0xd30 has a premature terminator entry at offset 0xd40
warning: address range table at offset 0xd60 has a premature terminator entry at offset 0xd70
warning: address range table at offset 0xd90 has a premature terminator entry at offset 0xda0
warning: address range table at offset 0xdc0 has a premature terminator entry at offset 0xdd0
warning: address range table at offset 0xdf0 has a premature terminator entry at offset 0xe00
    #0 0x322ef449 in NYql::NUdf::TUnboxedValuePod::Ref /-S/contrib/ydb/library/yql/public/udf/udf_value_inl.h:649:5
    #1 0x322ef449 in NYql::NUdf::TUnboxedValue::TUnboxedValue /-S/contrib/ydb/library/yql/public/udf/udf_value_inl.h:302:5
    #2 0x322ef449 in NKikimr::NMiniKQL::(anonymous namespace)::TSqueezeMapFlowWrapper<NKikimr::NMiniKQL::(anonymous namespace)::THashedSingleFixedCompactMapAccumulator<unsigned long, false, true>>::TState::Insert(NYql::NUdf::TUnboxedValuePod, NYql::NUdf::TUnboxedValuePod) /-B/contrib/ydb/library/yql/minikql/comp_nodes/llvm14/mkql_todict.cpp:1406:31
    #3 0x7fa6b4c07b51  (<unknown module>)
    #4 0x359ca135 in NYql::NUdf::TBoxedValueAccessor::WideFetch /-S/contrib/ydb/library/yql/public/udf/udf_value_inl.h:282:18
    #5 0x359ca135 in NYql::NUdf::TUnboxedValuePod::WideFetch /-S/contrib/ydb/library/yql/public/udf/udf_value_inl.h:636:12
    #6 0x359ca135 in NYql::NDq::TDqTaskRunner::FetchAndDispatch() /-S/contrib/ydb/library/yql/dq/runtime/dq_tasks_runner.cpp:916:61
    #7 0x359ae67a in NYql::NDq::TDqTaskRunner::Run() /-S/contrib/ydb/library/yql/dq/runtime/dq_tasks_runner.cpp:723:26
    #8 0x38f8dac3 in NYql::NDq::TDqSyncComputeActorBase<NKikimr::NKqp::TKqpComputeActor>::DoExecuteImpl() /-S/contrib/ydb/library/yql/dq/actors/compute/dq_sync_compute_actor_base.h:32:41
    #9 0x38f77f01 in NYql::NDq::TDqComputeActorBase<NKikimr::NKqp::TKqpComputeActor, NYql::NDq::TComputeActorAsyncInputHelperSync>::DoExecute() /-S/contrib/ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h:293:17
    #10 0x38f9c55e in NYql::NDq::TDqComputeActorBase<NKikimr::NKqp::TKqpComputeActor, NYql::NDq::TComputeActorAsyncInputHelperSync>::HandleExecuteBase(TAutoPtr<NActors::TEventHandle<NYql::NDq::TEvDqCompute::TEvChannelsInfo>, TDelete>&) /-S/contrib/ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h:1037:13
    #11 0x38f7251f in NKikimr::NKqp::TSchedulableComputeActorBase<NKikimr::NKqp::TKqpComputeActor>::BaseStateFuncBody /-S/contrib/ydb/core/kqp/runtime/kqp_compute_scheduler.h:178:24
    #12 0x38f7251f in NKikimr::NKqp::TKqpComputeActor::StateFunc(TAutoPtr<NActors::IEventHandle, TDelete>&) /-S/contrib/ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp:137:17
    #13 0x15a1a55a in NActors::TGenericExecutorThread::TProcessingResult NActors::TGenericExecutorThread::Execute<NActors::TMailboxTable::THTSwapMailbox>(NActors::TMailboxTable::THTSwapMailbox*, unsigned int, bool) /-S/contrib/ydb/library/actors/core/executor_thread.cpp:251:28
    #14 0x15a030a1 in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*)::$_0::operator()(unsigned int, bool) const /-S/contrib/ydb/library/actors/core/executor_thread.cpp:440:25
    #15 0x15a02385 in NActors::TGenericExecutorThread::ProcessExecutorPool(NActors::IExecutorPool*) /-S/contrib/ydb/library/actors/core/executor_thread.cpp:493:13
    #16 0x15a0463f in NActors::TExecutorThread::ThreadProc() /-S/contrib/ydb/library/actors/core/executor_thread.cpp:524:9
    #17 0x12e6ee02 in (anonymous namespace)::TPosixThread::ThreadProxy(void*) /-S/util/system/thread.cpp:244:20
    #18 0x7fa6b58e9608 in start_thread /build/glibc-LcI20x/glibc-2.31/nptl/pthread_create.c:477:8

#19 0x7fa6b5809352 in __clone /build/glibc-LcI20x/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
SUMMARY: MemorySanitizer: use-of-uninitialized-value /-S/contrib/ydb/library/yql/public/udf/udf_value_inl.h:649:5 in NYql::NUdf::TUnboxedValuePod::Ref
Exiting

**Comment by dcherednik** [comment]
related llvm issue
https://github.com/llvm/llvm-project/commit/f0ca0a324fd5d32285ec081616b01f23c8fc635b
